QUESTIONS = {
   "Section 1: Logic": [
        # =============================================
        # CATEGORY A: NUMBER SERIES
        # =============================================
        {"q": "Look at this series: 2, 4, 6, 8, 10, ... What number should come next?", "options": ["11", "12", "13", "14"], "answer": "12", "explanation": "Simple addition series: each number increases by 2."},
        {"q": "Look at this series: 2, 4, 8, 14, ?, 30. What number should come next?", "options": ["20", "22", "24", "26"], "answer": "22", "explanation": "Differences increase: +2, +4, +6, +8, +10. So 14+8=22."},
        {"q": "Look at this series: 1, 1, 2, 3, 5, 8, ... What number should come next?", "options": ["10", "11", "12", "13"], "answer": "13", "explanation": "Fibonacci sequence: each number is the sum of the two before it. 5+8=13."},
        {"q": "Look at this series: 3, 6, 12, 24, ... What number should come next?", "options": ["36", "40", "48", "50"], "answer": "48", "explanation": "Each number is multiplied by 2. 24×2=48."},
        {"q": "Look at this series: 5, 10, 20, 40, ... What number should come next?", "options": ["60", "70", "80", "90"], "answer": "80", "explanation": "Each number is multiplied by 2. 40×2=80."},
        {"q": "Look at this series: 1, 1, 2, 3, 5, ... What number should come next?", "options": ["6", "7", "8", "9"], "answer": "8", "explanation": "Fibonacci sequence: 3+5=8."},
        {"q": "Look at this series: 2, 6, 18, 54, ... What number should come next?", "options": ["108", "150", "162", "200"], "answer": "162", "explanation": "Each number is multiplied by 3. 54×3=162."},
        {"q": "Look at this series: 3, 9, 27, ... What number should come next?", "options": ["54", "72", "81", "90"], "answer": "81", "explanation": "Each number is multiplied by 3. 27×3=81."},
        {"q": "Look at this series: 100, 90, 80, 70, ... What number should come next?", "options": ["50", "55", "60", "65"], "answer": "60", "explanation": "Each number decreases by 10. 70-10=60."},
        {"q": "Look at this series: 100, 95, 85, 70, ... What number should come next?", "options": ["50", "55", "60", "65"], "answer": "50", "explanation": "Differences increase: -5, -10, -15, -20. So 70-20=50."},
        {"q": "Look at this series: 58, 52, 46, 40, 34, ... What number should come next?", "options": ["26", "28", "30", "32"], "answer": "28", "explanation": "Each number decreases by 6. 34-6=28."},
        {"q": "Look at this series: 544, 509, 474, 439, ... What number should come next?", "options": ["404", "414", "420", "445"], "answer": "404", "explanation": "Each number decreases by 35. 439-35=404."},
        {"q": "Look at this series: 201, 202, 204, 207, ... What number should come next?", "options": ["205", "208", "210", "211"], "answer": "211", "explanation": "Differences increase: +1, +2, +3, +4. So 207+4=211."},
        {"q": "Look at this series: 8, 22, 8, 28, 8, ... What number should come next?", "options": ["9", "29", "32", "34"], "answer": "34", "explanation": "The number 8 alternates. The other series: 22, 28, 34 (adds 6 each time)."},
        {"q": "Look at this series: 80, 10, 70, 15, 60, ... What number should come next?", "options": ["20", "25", "30", "50"], "answer": "20", "explanation": "Two alternating patterns: 80,70,60 (subtract 10) and 10,15,20 (add 5)."},
        {"q": "Look at this series: 36, 34, 30, 28, 24, ... What number should come next?", "options": ["20", "22", "23", "26"], "answer": "22", "explanation": "Alternating subtraction: -2, -4, -2, -4. So 24-2=22."},
        {"q": "Look at this series: 22, 21, 23, 22, 24, 23, ... What number should come next?", "options": ["22", "24", "25", "26"], "answer": "25", "explanation": "Alternating pattern: -1, +2 repeating. 23+2=25."},
        {"q": "Look at this series: 3, 4, 7, 8, 11, 12, ... What number should come next?", "options": ["7", "10", "14", "15"], "answer": "15", "explanation": "Alternating +1, +3 pattern. 12+3=15."},
        {"q": "Look at this series: 1000, 200, 40, ... What number should come next?", "options": ["8", "10", "15", "20"], "answer": "8", "explanation": "Each number is divided by 5. 40÷5=8."},
        {"q": "Look at this series: 7, 10, 8, 11, 9, 12, ... What number should come next?", "options": ["7", "10", "12", "13"], "answer": "10", "explanation": "Two alternating patterns: 7,8,9,10 (add 1) and 10,11,12 (add 1)."},
        {"q": "Look at this series: 14, 28, 20, 40, 32, 64, ... What number should come next?", "options": ["52", "56", "96", "128"], "answer": "56", "explanation": "Two alternating patterns: ×2, then -8. 64-8=56."},
        {"q": "Look at this series: 40, 40, 47, 47, 54, ... What number should come next?", "options": ["40", "44", "54", "61"], "answer": "54", "explanation": "Each number repeats then increases by 7. After 54, it repeats."},
        {"q": "Look at this series: 21, 9, 21, 11, 21, 13, ... What number should come next?", "options": ["14", "15", "21", "23"], "answer": "21", "explanation": "The number 21 alternates. Other series: 9,11,13 (adds 2). After 13, repeat 21."},
        {"q": "Look at this series: 53, 53, 40, 40, 27, 27, ... What number should come next?", "options": ["12", "14", "27", "53"], "answer": "14", "explanation": "Each number repeats, then 13 is subtracted. 27-13=14."},

        # =============================================
        # CATEGORY B: LETTER/PATTERN SERIES
        # =============================================
        {"q": "Complete the pattern: A, C, E, G, ?", "options": ["H", "I", "J", "K"], "answer": "I", "explanation": "Letters skip one position (skip B, D, F, H). Next letter is I."},
        {"q": "Letter pattern: B, E, H, K, ?", "options": ["M", "N", "O", "P"], "answer": "N", "explanation": "Each letter advances by 3 positions. K+3=N."},
        {"q": "Letter pattern: QPO, NML, KJI, ?, EDC", "options": ["HGF", "CAB", "JKL", "GHI"], "answer": "HGF", "explanation": "Each group is 3 consecutive letters in reverse, starting from Q,N,K,H,E."},
        {"q": "Letter pattern: JAK, KBL, LCM, MDN, ?", "options": ["OEP", "NEO", "MEN", "PFQ"], "answer": "NEO", "explanation": "First letter advances by 1 (J,K,L,M,N), middle by 1 (A,B,C,D,E), third by 1 (K,L,M,N,O)."},
        {"q": "Letter pattern: SCD, TEF, UGH, ?, WKL", "options": ["CMN", "UJI", "VIJ", "IJT"], "answer": "VIJ", "explanation": "First letter: S,T,U,V,W. Second and third letters advance by 2 each step."},
        {"q": "Letter pattern: BCB, DED, FGF, HIH, ?", "options": ["JKJ", "HJH", "IJI", "JHJ"], "answer": "JKJ", "explanation": "First & third letters are the same, advancing alphabetically by 2. Middle advances by 1."},

        # =============================================
        # CATEGORY C: VERBAL CLASSIFICATION
        # =============================================
        {"q": "Which word does NOT belong with the others?", "options": ["Swift", "Python", "Java", "HTML"], "answer": "HTML", "explanation": "Swift, Python, Java are programming languages. HTML is a markup language."},
        {"q": "Which word does NOT belong with the others? Leopard, Cougar, Elephant, Lion", "options": ["Leopard", "Cougar", "Elephant", "Lion"], "answer": "Elephant", "explanation": "Leopard, cougar, lion are big cats. Elephant is not."},
        {"q": "Which word does NOT belong with the others? Couch, Rug, Table, Chair", "options": ["Couch", "Rug", "Table", "Chair"], "answer": "Rug", "explanation": "Couch, table, chair are furniture for sitting/surfaces. Rug is a floor covering."},
        {"q": "Which word does NOT belong with the others? Tulip, Rose, Bud, Daisy", "options": ["Tulip", "Rose", "Bud", "Daisy"], "answer": "Bud", "explanation": "Tulip, rose, daisy are types of flowers. A bud is not a type of flower."},
        {"q": "Which word does NOT belong with the others? Tire, Steering Wheel, Engine, Car", "options": ["Tire", "Steering Wheel", "Engine", "Car"], "answer": "Car", "explanation": "Tire, steering wheel, engine are parts of a car. Car is the whole thing."},
        {"q": "Which word does NOT belong with the others? Parsley, Basil, Dill, Mayonnaise", "options": ["Parsley", "Basil", "Dill", "Mayonnaise"], "answer": "Mayonnaise", "explanation": "Parsley, basil, dill are herbs. Mayonnaise is a condiment/sauce."},
        {"q": "Which word does NOT belong with the others? Noun, Preposition, Punctuation, Adverb", "options": ["Noun", "Preposition", "Punctuation", "Adverb"], "answer": "Punctuation", "explanation": "Noun, preposition, adverb are parts of speech. Punctuation is not."},
        {"q": "Which word does NOT belong with the others? Cornea, Retina, Pupil, Vision", "options": ["Cornea", "Retina", "Pupil", "Vision"], "answer": "Vision", "explanation": "Cornea, retina, pupil are parts of the eye. Vision is a function, not a part."},
        {"q": "Which word does NOT belong with the others? Unique, Beautiful, Rare, Exceptional", "options": ["Unique", "Beautiful", "Rare", "Exceptional"], "answer": "Beautiful", "explanation": "Unique, rare, exceptional are synonyms (uncommon). Beautiful has a different meaning."},
        {"q": "Which word does NOT belong with the others? Biology, Chemistry, Theology, Zoology", "options": ["Biology", "Chemistry", "Theology", "Zoology"], "answer": "Theology", "explanation": "Biology, chemistry, zoology are natural sciences. Theology is the study of religion."},
        {"q": "Which word does NOT belong with the others? Inch, Ounce, Centimeter, Yard", "options": ["Inch", "Ounce", "Centimeter", "Yard"], "answer": "Ounce", "explanation": "Inch, centimeter, yard measure length. Ounce measures weight."},
        {"q": "Which word does NOT belong with the others? Mayor, Lawyer, Governor, Senator", "options": ["Mayor", "Lawyer", "Governor", "Senator"], "answer": "Lawyer", "explanation": "Mayor, governor, senator are elected officials. Lawyer is not an elected office."},

        # =============================================
        # CATEGORY D: ESSENTIAL PART
        # =============================================
        {"q": "A 'book' could not exist without...", "options": ["Paper", "Pages", "Pictures", "Learning"], "answer": "Pages", "explanation": "A book must have pages. Pictures and learning are optional."},
        {"q": "A 'guitar' could not exist without...", "options": ["Band", "Teacher", "Songs", "Strings"], "answer": "Strings", "explanation": "A guitar must have strings. Band, teacher, and songs are optional."},
        {"q": "A 'shoe' could not exist without...", "options": ["Sole", "Leather", "Laces", "Walking"], "answer": "Sole", "explanation": "A shoe must have a sole. Leather, laces, and walking are optional."},
        {"q": "'Respiration' could not exist without...", "options": ["Mouth", "Circulation", "Oxygen", "Carbon Monoxide"], "answer": "Oxygen", "explanation": "Respiration requires oxygen. Mouth, circulation, carbon monoxide are optional."},
        {"q": "An 'election' could not exist without...", "options": ["President", "Voter", "November", "Nation"], "answer": "Voter", "explanation": "An election requires voters. President, November, nation are optional."},
        {"q": "'Swimming' could not exist without...", "options": ["Pool", "Bathing Suit", "Water", "Life Jacket"], "answer": "Water", "explanation": "Swimming requires water. Pool, bathing suit, life jacket are optional."},
        {"q": "A 'language' could not exist without...", "options": ["Tongue", "Slang", "Writing", "Words"], "answer": "Words", "explanation": "A language must have words. Tongue, slang, writing are optional."},
        {"q": "A 'hurricane' could not exist without...", "options": ["Beach", "Cyclone", "Damage", "Wind"], "answer": "Wind", "explanation": "A hurricane requires wind. Beach, damage are optional."},
        {"q": "A 'recipe' could not exist without...", "options": ["Desserts", "Directions", "Cookbook", "Utensils"], "answer": "Directions", "explanation": "A recipe must have directions/instructions. Desserts, cookbook are optional."},
        {"q": "A 'wedding' could not exist without...", "options": ["Love", "Church", "Ring", "Marriage"], "answer": "Marriage", "explanation": "A wedding must involve marriage. Love, church, ring are optional."},
        {"q": "'Knowledge' could not exist without...", "options": ["School", "Teacher", "Textbook", "Learning"], "answer": "Learning", "explanation": "Knowledge requires learning. School, teacher, textbook are optional."},
        {"q": "A 'contract' could not exist without...", "options": ["Agreement", "Document", "Written", "Attorney"], "answer": "Agreement", "explanation": "A contract requires an agreement. Document, written form, attorney are optional."},

        # =============================================
        # CATEGORY E: VERBAL ANALOGIES
        # =============================================
        {"q": "Paper is to Wood as Cloth is to ?", "options": ["Clothing", "Cotton", "Thread", "Scissors"], "answer": "Cotton", "explanation": "Paper is made from wood; cloth is made from cotton."},
        {"q": "Cup is to Coffee as Bowl is to ?", "options": ["Dish", "Soup", "Spoon", "Food"], "answer": "Soup", "explanation": "A cup holds coffee; a bowl holds soup."},
        {"q": "Artist is to Painting as Senator is to ?", "options": ["Attorney", "Law", "Politician", "Constituents"], "answer": "Law", "explanation": "An artist creates a painting; a senator creates a law."},
        {"q": "Careful is to Cautious as Boastful is to ?", "options": ["Arrogant", "Humble", "Joyful", "Suspicious"], "answer": "Arrogant", "explanation": "Careful and cautious are synonyms; boastful and arrogant are synonyms."},
        {"q": "Secretly is to Openly as Silently is to ?", "options": ["Scarcely", "Impolitely", "Noisily", "Quietly"], "answer": "Noisily", "explanation": "Secretly and openly are antonyms; silently and noisily are antonyms."},
        {"q": "Yard is to Inch as Quart is to ?", "options": ["Gallon", "Ounce", "Milk", "Liquid"], "answer": "Ounce", "explanation": "A yard is a larger unit than an inch; a quart is a larger unit than an ounce."},
        {"q": "Elated is to Despondent as Enlightened is to ?", "options": ["Aware", "Ignorant", "Miserable", "Tolerant"], "answer": "Ignorant", "explanation": "Elated and despondent are antonyms; enlightened and ignorant are antonyms."},
        {"q": "Optimist is to Cheerful as Pessimist is to ?", "options": ["Gloomy", "Mean", "Petty", "Helpful"], "answer": "Gloomy", "explanation": "An optimist is cheerful; a pessimist is gloomy."},
        {"q": "Sponge is to Porous as Rubber is to ?", "options": ["Massive", "Solid", "Elastic", "Inflexible"], "answer": "Elastic", "explanation": "A sponge is porous by nature; rubber is elastic by nature."},
        {"q": "Pen is to Poet as Needle is to ?", "options": ["Thread", "Button", "Sewing", "Tailor"], "answer": "Tailor", "explanation": "A pen is a poet's tool; a needle is a tailor's tool."},
        {"q": "Odometer is to Mileage as Compass is to ?", "options": ["Speed", "Hiking", "Needle", "Direction"], "answer": "Direction", "explanation": "An odometer measures mileage; a compass measures direction."},
        {"q": "Conductor is to Orchestra as Skipper is to ?", "options": ["Jockey", "Hay", "Tractor", "Crew"], "answer": "Crew", "explanation": "A conductor leads an orchestra; a skipper leads a crew."},

        # =============================================
        # CATEGORY F: DEDUCTIVE LOGIC
        # =============================================
        {"q": "All programmers are humans. Some humans like coffee. Do all programmers like coffee?", "options": ["Yes", "Maybe", "No", "Cannot be determined"], "answer": "No", "explanation": "Only some humans like coffee, so we cannot conclude all programmers like coffee."},
        {"q": "All laptops need electricity. A MacBook is a laptop. Therefore...", "options": ["MacBook doesn't need electricity", "MacBook needs electricity", "MacBook is a computer", "None of the above"], "answer": "MacBook needs electricity", "explanation": "Syllogism: All laptops need electricity + MacBook is a laptop = MacBook needs electricity."},
        {"q": "All CS students are good at coding. Alex is a CS student. Alex is not good at coding. This statement is...", "options": ["True", "False/Contradictory", "Alex is not a CS student", "Alex is good at design"], "answer": "False/Contradictory", "explanation": "Contradiction: if all CS students are good at coding and Alex is a CS student, then Alex must be good at coding."},
        {"q": "Some doctors are musicians. All musicians are creative. Therefore...", "options": ["All doctors are creative", "Some doctors are creative", "No doctors are creative", "All musicians are doctors"], "answer": "Some doctors are creative", "explanation": "Some doctors = musicians, all musicians = creative, so some doctors are creative."},
        {"q": "All roses are flowers. Some flowers wilt quickly. Do roses wilt quickly?", "options": ["Yes", "No", "Not necessarily", "Impossible"], "answer": "Not necessarily", "explanation": "Only some flowers wilt quickly; we can't be sure roses are among them."},
        {"q": "All A are B, and all B are C. Therefore...", "options": ["All A are C", "All C are A", "Cannot be concluded", "All B are A"], "answer": "All A are C", "explanation": "Transitive syllogism: A⊂B and B⊂C, therefore A⊂C."},
        {"q": "Tanya is older than Eric. Cliff is older than Tanya. Eric is older than Cliff. If statements 1 and 2 are true, statement 3 is...", "options": ["True", "False", "Uncertain"], "answer": "False", "explanation": "Cliff > Tanya > Eric, so Eric is NOT older than Cliff."},
        {"q": "Blueberries cost more than strawberries. Blueberries cost less than raspberries. Raspberries cost more than both. If statements 1-2 are true, statement 3 is...", "options": ["True", "False", "Uncertain"], "answer": "True", "explanation": "Raspberry > Blueberry > Strawberry, so raspberries are indeed the most expensive."},
        {"q": "All offices on the 9th floor have carpet. No carpet is pink. No office on the 9th floor has pink carpet. If statements 1-2 are true, statement 3 is...", "options": ["True", "False", "Uncertain"], "answer": "True", "explanation": "If no carpet is pink, then 9th floor offices also don't have pink carpet."},
        {"q": "Mara runs faster than Gail. Lily runs faster than Mara. Gail runs faster than Lily. If statements 1-2 are true, statement 3 is...", "options": ["True", "False", "Uncertain"], "answer": "False", "explanation": "Lily > Mara > Gail, so Gail does NOT run faster than Lily."},
        {"q": "Battery X lasts longer than Y. Battery Y doesn't last as long as Z. Battery Z lasts longer than X. If statements 1-2 are true, statement 3 is...", "options": ["True", "False", "Uncertain"], "answer": "Uncertain", "explanation": "X>Y and Z>Y, but the relationship between X and Z cannot be determined."},
        {"q": "Monday's temperature was lower than Tuesday's. Wednesday's was lower than Tuesday's. Monday's was higher than Wednesday's. If statements 1-2 are true, statement 3 is...", "options": ["True", "False", "Uncertain"], "answer": "Uncertain", "explanation": "Tuesday > Monday and Tuesday > Wednesday, but Monday vs Wednesday is undetermined."},
        {"q": "Fact: All dogs like to run. Some dogs like to swim. Some dogs look like their owners. Therefore: Dogs that like to swim also like to run.", "options": ["True", "False", "Uncertain"], "answer": "True", "explanation": "ALL dogs like to run, so the subset that likes to swim must also like to run."},

        # =============================================
        # CATEGORY G: ARTIFICIAL LANGUAGE
        # =============================================
        {"q": "granamelke = big tree, pinimelke = little tree, melkehoon = tree house. Which word means 'big house'?", "options": ["granahoon", "pinishur", "pinihoon", "melkegrana"], "answer": "granahoon", "explanation": "grana=big, melke=tree, hoon=house. Big house = grana+hoon."},
        {"q": "moolokarn = blue sky, wilkospadi = bicycle race, moolowilko = blue bicycle. Which word could mean 'racecar'?", "options": ["wilkozwet", "spadiwilko", "moolobreil", "spadivolo"], "answer": "spadivolo", "explanation": "moolo=blue, wilko=bicycle, spadi=race, karn=sky. Racecar = spadi+volo(car)."},
        {"q": "daftafoni = advisement, imodafta = misadvise, imolokti = misconduct. Which word could mean 'statement'?", "options": ["kratafoni", "kratadafta", "loktifoni", "daftaimo"], "answer": "kratafoni", "explanation": "dafta=advise, foni=statement/-ment, imo=mis-. Statement = krata+foni."},
        {"q": "dionot = oak tree, blyonot = oak leaf, blycrin = maple leaf. Which word could mean 'maple syrup'?", "options": ["blymuth", "hupponot", "patricrin", "crinweel"], "answer": "crinweel", "explanation": "dio=tree, not=oak, bly=leaf, crin=maple. Maple syrup = crin+weel(syrup)."},
        {"q": "morpirquat = birdhouse, beelmorpir = bluebird, beelclak = bluebell. Which word could mean 'houseguest'?", "options": ["morpirhunde", "beelmoki", "quathunde", "clakquat"], "answer": "quathunde", "explanation": "morpir=bird, quat=house, beel=blue, clak=bell. Houseguest = quat+hunde(guest)."},
        {"q": "jalkamofti = happy birthday, moftihoze = birthday party, mentogunn = goodness. Which word could mean 'happiness'?", "options": ["jalkagunn", "mentohoze", "moftihoze", "hozemento"], "answer": "jalkagunn", "explanation": "jalka=happy, mofti=birthday, gunn=quality/-ness, mento=good. Happiness = jalka+gunn."},
        {"q": "mallonpiml = blue light, mallontif = blueberry, arpantif = raspberry. Which word could mean 'lighthouse'?", "options": ["tifmallon", "pimlarpan", "mallonarpan", "pimldoken"], "answer": "pimldoken", "explanation": "mallon=blue, piml=light, tif=berry, arpan=rasp. Lighthouse = piml+doken(house)."},
        {"q": "relftaga = carefree, otaga = careful, fertaga = careless. Which word could mean 'aftercare'?", "options": ["zentaga", "tagafer", "tagazen", "relffer"], "answer": "tagazen", "explanation": "taga=care, relf=free, o=ful, fer=less. Aftercare = taga+zen(after)."},

        # =============================================
        # CATEGORY H: MATCHING DEFINITIONS & JUDGMENT
        # =============================================
        {"q": "Restitution = compensating someone for property damage. Which is the best example?", "options": ["Jake borrows Lisa's camera, the lens breaks, Jake pays for repair", "Rebecca borrows a car, returns it with no gas, only apologizes", "Aaron finds a burst pipe in Tom's apartment and calls a plumber", "Lisa suspects a pothole caused her flat tire, asks boss to pay"], "answer": "Jake borrows Lisa's camera, the lens breaks, Jake pays for repair", "explanation": "Restitution is direct compensation. Jake damaged the camera and pays for repair."},
        {"q": "Speculation = assuming something based on inconclusive evidence. Which is the best example?", "options": ["Francine reads the handbook and wears jeans on Casual Friday", "Mary sits in traffic for 30 minutes and wishes she took the train", "Jennifer consults guidebooks and feels confident about her trip", "Emily opens the door in tears; Theo guesses there's been a death in the family"], "answer": "Emily opens the door in tears; Theo guesses there's been a death in the family", "explanation": "Theo makes an assumption based on uncertain evidence (crying could mean many things)."},
        {"q": "Reentry = a person leaves their social system and then returns. Which is the best example?", "options": ["Jacob moves to manage a new restaurant across town", "Catherine is studying abroad in France for a year", "Malcolm is readjusting to civilian life after 2 years of military service overseas", "Sharon decides she can no longer share an apartment with her roommate"], "answer": "Malcolm is readjusting to civilian life after 2 years of military service overseas", "explanation": "Malcolm left his social system (overseas military) and returned to civilian life."},
        {"q": "Embellishing the Truth = adding fictitious details or exaggerating facts. Which is the best example?", "options": ["Isabel tells coworkers the theater play was excellent", "A realtor describes a house 11 blocks from the ocean as 'prime waterfront property'", "Fred, who taught for 10 years, describes himself as very experienced", "A basketball coach says only the most talented players will get scholarships"], "answer": "A realtor describes a house 11 blocks from the ocean as 'prime waterfront property'", "explanation": "Describing a house 11 blocks from the ocean as 'waterfront' is a clear exaggeration."},
        {"q": "Informal Gathering = a group of people get together casually. Which is the best example?", "options": ["The book club meets on the first Thursday of every month", "After hearing about his promotion, Jeremy and coworkers go for a drink after work", "Mary sends out 25 invitations for a bridal shower", "Clara always happens to run into Peter at the Mexican restaurant"], "answer": "After hearing about his promotion, Jeremy and coworkers go for a drink after work", "explanation": "Jeremy and coworkers spontaneously go for drinks — casual and unplanned."},

        # =============================================
        # CATEGORY I: COMPLEX LOGIC PUZZLES
        # =============================================
        {"q": "A train travels at 60 km/h. How long does it take to travel 180 km?", "options": ["2 hours", "2.5 hours", "3 hours", "4 hours"], "answer": "3 hours", "explanation": "180 ÷ 60 = 3 hours."},
        {"q": "If today is Monday, what day will it be 100 days from now?", "options": ["Tuesday", "Wednesday", "Thursday", "Friday"], "answer": "Wednesday", "explanation": "100 ÷ 7 = 14 remainder 2. Monday + 2 days = Wednesday."},
        {"q": "A father's age is 3 times his child's. If the child is 15, how old will the father be in 5 years?", "options": ["45", "50", "55", "60"], "answer": "50", "explanation": "Father's current age = 3×15 = 45. In 5 years = 45+5 = 50."},
        {"q": "Andy is older than Ben. Cindy is younger than Ben. Who is the youngest?", "options": ["Andy", "Ben", "Cindy", "None"], "answer": "Cindy", "explanation": "Andy > Ben > Cindy. Cindy is the youngest."},
        {"q": "If 5 machines produce 5 items in 5 minutes, how long for 100 machines to produce 100 items?", "options": ["100 minutes", "50 minutes", "10 minutes", "5 minutes"], "answer": "5 minutes", "explanation": "1 machine = 1 item per 5 minutes. 100 machines = 100 items per 5 minutes."},
        {"q": "Which is heavier: 1 kg of Cotton or 1 kg of Iron?", "options": ["Cotton", "Iron", "They weigh the same", "Cannot be determined"], "answer": "They weigh the same", "explanation": "1 kg = 1 kg, regardless of the material's volume."},
        {"q": "A store offers a 20% discount. Original price is $100. What is the discounted price?", "options": ["$70", "$80", "$90", "$85"], "answer": "$80", "explanation": "20% discount = $20 off. Final price = $100 - $20 = $80."},
        {"q": "How many times does the digit 9 appear between 1 and 100?", "options": ["10", "11", "19", "20"], "answer": "20", "explanation": "Tens place: 90-99 (10 nines). Ones place: 9,19,29,...,99 (10 nines). Total = 20."},
        {"q": "If p=3 and q=4, what is the value of p² + q²?", "options": ["7", "12", "25", "49"], "answer": "25", "explanation": "3² + 4² = 9 + 16 = 25."},
        {"q": "If 1 person can finish a job in 10 days, how many days do 2 people need?", "options": ["5", "10", "15", "20"], "answer": "5", "explanation": "Inversely proportional: 2 people = 10/2 = 5 days."},
        {"q": "If 1 book costs $5, how much do 3 books cost?", "options": ["$10", "$15", "$20", "$25"], "answer": "$15", "explanation": "3 × $5 = $15."},
        {"q": "If 10 workers finish a job in 2 days, how many days do 5 workers need?", "options": ["2", "3", "4", "5"], "answer": "4", "explanation": "Inversely proportional: 10×2 = 5×x, x = 4 days."},
        {"q": "5 people are in a queue. Ed is ahead of Dave. Dave is behind Amy. Amy is behind Bob. Who is at the front?", "options": ["Ed", "Dave", "Amy", "Bob"], "answer": "Bob", "explanation": "Order from front: Bob > Amy > Ed > Dave. Bob is at the front."},
        {"q": "4 friends share pizza; the oldest gets extra. Randy is 2 months older than Greg. Greg is 3 months younger than Ned. Kent is 1 month older than Greg. Who gets extra?", "options": ["Randy", "Greg", "Ned", "Kent"], "answer": "Ned", "explanation": "Ned > Randy > Kent > Greg. Ned is the oldest."},
        {"q": "New math chair is picked by seniority. West < Temple, West > Brody. Rhodes > West, Rhodes < Temple. Temple declines. Who is the new chair?", "options": ["Rhodes", "Temple", "West", "Brody"], "answer": "Rhodes", "explanation": "Order: Temple > Rhodes > West > Brody. Temple declines, so Rhodes."},
        {"q": "Henry is in seat 253. Marla is to his right in 254. George is to his left. Inez is to George's left. What seat is Inez in?", "options": ["251", "254", "255", "256"], "answer": "251", "explanation": "George is in seat 252 (left of Henry). Inez is left of George = seat 251."},
    ],

   "Section 2: Programming (Swift Focus)": [
        # =============================================
        # BASICS: Variables, Constants, Types
        # =============================================
        {"q": "How do you declare a variable whose value can change in Swift?", "options": ["let", "var", "const", "static"], "answer": "var", "explanation": "'var' declares a mutable variable. 'let' declares a constant."},
        {"q": "How do you declare a constant (immutable value) in Swift?", "options": ["var", "let", "const", "final"], "answer": "let", "explanation": "'let' declares a constant whose value cannot be changed after assignment."},
        {"q": "Which of the following is the correct way to declare a String variable in Swift?", "options": ["var name: String = \"John\"", "String name = \"John\"", "let name = String(\"John\")", "dim name as String = \"John\""], "answer": "var name: String = \"John\"", "explanation": "Swift uses 'var name: Type = value' syntax for variable declaration."},
        {"q": "What is the data type for decimal numbers (high precision) in Swift?", "options": ["Int", "String", "Double", "Bool"], "answer": "Double", "explanation": "Double is the 64-bit floating-point type in Swift for decimal numbers."},
        {"q": "What data type only has the values true or false?", "options": ["Binary", "Boolean", "Logic", "Bit"], "answer": "Boolean", "explanation": "Bool (Boolean) type can only be true or false in Swift."},
        {"q": "What is 'Type Inference' in Swift?", "options": ["The compiler guesses the data type from the assigned value", "A way to force a type change", "A debugging technique", "A way to declare functions"], "answer": "The compiler guesses the data type from the assigned value", "explanation": "Swift can automatically infer the type. e.g., 'var x = 5' is inferred as Int."},
        {"q": "What is the output of: print(type(of: 5.0))?", "options": ["Int", "Float", "Double", "Number"], "answer": "Double", "explanation": "Swift infers decimal literals as Double by default, not Float."},
        {"q": "What does 'Any' type mean in Swift?", "options": ["Only String", "Only Integer", "Can represent an instance of any type", "No data allowed"], "answer": "Can represent an instance of any type", "explanation": "'Any' can represent any type at all, including function types."},
        {"q": "What is the difference between Float and Double in Swift?", "options": ["Float is 64-bit, Double is 32-bit", "Float is 32-bit, Double is 64-bit", "They are identical", "Float is for strings"], "answer": "Float is 32-bit, Double is 64-bit", "explanation": "Float has 32-bit precision (~6 digits), Double has 64-bit precision (~15 digits)."},
        {"q": "How do you create a multi-line string in Swift?", "options": ["Using triple quotes \"\"\"...\"\"\"", "Using \\n in a regular string", "Using String.multiline()", "Multi-line strings are not supported"], "answer": "Using triple quotes \"\"\"...\"\"\"", "explanation": "Swift uses triple double-quotes for multi-line string literals."},

        # =============================================
        # OPERATORS & EXPRESSIONS
        # =============================================
        {"q": "What is the output of: print(5 / 2) if both are Integers?", "options": ["2.5", "2", "3", "Error"], "answer": "2", "explanation": "Integer division truncates the decimal. 5/2 = 2 (not 2.5)."},
        {"q": "What does the '??' (Nil-Coalescing Operator) do?", "options": ["Provides a default value if an optional is nil", "Multiplies two numbers", "Compares two strings", "Force unwraps a variable"], "answer": "Provides a default value if an optional is nil", "explanation": "Example: let name = optionalName ?? \"Guest\" — uses \"Guest\" if optionalName is nil."},
        {"q": "What does the '===' (triple equals) operator do?", "options": ["Compares values", "Checks if two references point to the same class instance", "Assigns a new value", "Checks data type"], "answer": "Checks if two references point to the same class instance", "explanation": "'===' is the identity operator — it checks if two variables reference the exact same object in memory."},
        {"q": "What is the result of: 10 % 3 in Swift?", "options": ["3", "1", "0", "3.33"], "answer": "1", "explanation": "The % operator returns the remainder. 10 ÷ 3 = 3 remainder 1."},
        {"q": "What does the ternary operator look like in Swift?", "options": ["condition ? valueIfTrue : valueIfFalse", "if condition then value", "condition ?? value", "condition ! value"], "answer": "condition ? valueIfTrue : valueIfFalse", "explanation": "Example: let result = age >= 18 ? \"Adult\" : \"Minor\""},

        # =============================================
        # STRINGS
        # =============================================
        {"q": "What is the correct way to concatenate 'Hello' and 'World' in Swift?", "options": ["\"Hello\" + \"World\"", "\"Hello\" . \"World\"", "\"Hello\" & \"World\"", "concat(\"Hello\", \"World\")"], "answer": "\"Hello\" + \"World\"", "explanation": "Swift uses the + operator to concatenate strings."},
        {"q": "In Swift, 'String Interpolation' uses the syntax...", "options": ["${}", "{}", "\\()", "#()"], "answer": "\\()", "explanation": "Example: \"Hello, \\(name)!\" — inserts the value of 'name' into the string."},
        {"q": "How do you check if a string is empty in Swift?", "options": ["str.length == 0", "str.isEmpty", "str == nil", "str.count() == 0"], "answer": "str.isEmpty", "explanation": "The .isEmpty property returns true if a string has no characters."},
        {"q": "What does str.count return for the string \"Hello\"?", "options": ["4", "5", "6", "Error"], "answer": "5", "explanation": "'Hello' has 5 characters: H-e-l-l-o."},
        {"q": "How do you convert an Int to a String in Swift?", "options": ["String(42)", "(String)42", "42.toString()", "str(42)"], "answer": "String(42)", "explanation": "Use the String initializer: String(42) returns \"42\"."},

        # =============================================
        # OPTIONALS
        # =============================================
        {"q": "What does the '!' symbol after a type (e.g., String!) mean?", "options": ["Optional", "Implicitly Unwrapped Optional", "Force Close", "Error"], "answer": "Implicitly Unwrapped Optional", "explanation": "An Implicitly Unwrapped Optional is assumed to have a value and is auto-unwrapped when accessed."},
        {"q": "What is an Optional in Swift?", "options": ["A variable that can hold any type", "A variable that can be nil (no value)", "A constant value", "A special array type"], "answer": "A variable that can be nil (no value)", "explanation": "An Optional says 'there IS a value, and it equals x' or 'there isn't a value at all (nil)'."},
        {"q": "What is 'Optional Binding' in Swift?", "options": ["Wrapping a value in an optional", "Using if-let or guard-let to safely unwrap an optional", "Converting nil to a default value", "Chaining optional calls"], "answer": "Using if-let or guard-let to safely unwrap an optional", "explanation": "if let value = optionalValue { ... } safely unwraps the optional."},
        {"q": "What happens if you force unwrap (!) a nil optional?", "options": ["Returns nil", "Returns 0", "The app crashes at runtime", "The compiler shows a warning"], "answer": "The app crashes at runtime", "explanation": "Force unwrapping a nil value causes a fatal runtime error (crash)."},
        {"q": "What is 'Optional Chaining' in Swift?", "options": ["Connecting multiple cables", "Calling properties/methods on an optional that might be nil", "Looping inside an optional", "Deleting an optional variable"], "answer": "Calling properties/methods on an optional that might be nil", "explanation": "Optional chaining lets you query properties on optionals that might be nil. Returns nil if any link is nil."},

        # =============================================
        # COLLECTIONS: Array, Set, Dictionary
        # =============================================
        {"q": "How do you check the number of elements in an array 'names'?", "options": ["names.length", "names.size", "names.count", "names.total"], "answer": "names.count", "explanation": "Swift uses .count to get the number of elements in a collection."},
        {"q": "How do you add a new element to the end of an Array?", "options": ["array.add(item)", "array.push(item)", "array.append(item)", "array.insert(item)"], "answer": "array.append(item)", "explanation": "Swift arrays use .append() to add elements to the end."},
        {"q": "Which Swift collection does NOT allow duplicate values?", "options": ["Array", "Dictionary", "Set", "Tuple"], "answer": "Set", "explanation": "A Set stores unique values only. Arrays allow duplicates."},
        {"q": "What is a Tuple in Swift?", "options": ["A type for storing a single value", "A group of multiple values in one compound value", "A function for looping", "Another name for Class"], "answer": "A group of multiple values in one compound value", "explanation": "A Tuple groups values together. Example: let person = (\"Alice\", 25)"},
        {"q": "How do you create an empty array of Integers in Swift?", "options": ["var arr = []", "var arr = [Int]()", "var arr = Array()", "var arr = new Int[]"], "answer": "var arr = [Int]()", "explanation": "Use [Int]() or Array<Int>() to create an empty Int array."},
        {"q": "How do you access the value for key \"name\" in a dictionary?", "options": ["dict.name", "dict[\"name\"]", "dict.get(\"name\")", "dict->name"], "answer": "dict[\"name\"]", "explanation": "Swift dictionaries use subscript syntax: dict[\"key\"] returns an optional value."},
        {"q": "What does array.filter { $0 % 2 == 0 } return?", "options": ["Odd numbers", "Even numbers", "All numbers", "Sum of numbers"], "answer": "Even numbers", "explanation": "filter keeps elements where the condition is true. $0 % 2 == 0 checks for even numbers."},
        {"q": "What is the output of: let x = [1,2].map { $0 * 2 }?", "options": ["[2, 4]", "[1, 2]", "[4, 2]", "Error"], "answer": "[2, 4]", "explanation": "map transforms each element. 1*2=2 and 2*2=4, so result is [2, 4]."},

        # =============================================
        # CONTROL FLOW: if, switch, loops
        # =============================================
        {"q": "What keyword is used to forcefully stop a loop?", "options": ["stop", "exit", "break", "halt"], "answer": "break", "explanation": "'break' immediately exits the current loop."},
        {"q": "Which loop evaluates the condition at the END of each iteration?", "options": ["for-in", "while", "repeat-while", "foreach"], "answer": "repeat-while", "explanation": "'repeat-while' runs the code block first, then checks the condition (like do-while in other languages)."},
        {"q": "What is the purpose of the 'guard' statement in Swift?", "options": ["To perform loops", "To exit a function early if a condition is not met", "To create a class", "To delete a variable"], "answer": "To exit a function early if a condition is not met", "explanation": "'guard' requires the condition to be true; otherwise, the else block must exit the scope."},
        {"q": "What does the 'continue' keyword do inside a loop?", "options": ["Stops the loop entirely", "Skips the rest of the current iteration and starts the next one", "Pauses the loop for 1 second", "Continues to the next function"], "answer": "Skips the rest of the current iteration and starts the next one", "explanation": "'continue' skips the remaining code in the current iteration and jumps to the next iteration."},
        {"q": "In a Swift 'switch' statement, do you need a 'break' at the end of each case?", "options": ["Yes, always required", "No, Swift does not fall through by default", "Only for the default case", "Only for Int cases"], "answer": "No, Swift does not fall through by default", "explanation": "Unlike C/Java, Swift switch cases don't fall through. No explicit 'break' is needed."},
        {"q": "What keyword allows a switch case to fall through to the next case?", "options": ["continue", "fallthrough", "next", "pass"], "answer": "fallthrough", "explanation": "The 'fallthrough' keyword explicitly makes execution fall through to the next case."},
        {"q": "How do you iterate over a range from 1 to 5 (inclusive) in Swift?", "options": ["for i in 1...5", "for i in 1..5", "for i in range(1,5)", "for (i=1; i<=5; i++)"], "answer": "for i in 1...5", "explanation": "The closed range operator '...' includes both endpoints: 1, 2, 3, 4, 5."},
        {"q": "What is the difference between '...' and '..<' range operators?", "options": ["'...' includes upper bound, '..<' excludes it", "They are identical", "'..<' includes upper bound, '...' excludes it", "'...' is for strings, '..<' is for numbers"], "answer": "'...' includes upper bound, '..<' excludes it", "explanation": "1...5 = [1,2,3,4,5] but 1..<5 = [1,2,3,4]. '..<' is a half-open range."},

        # =============================================
        # FUNCTIONS
        # =============================================
        {"q": "What is the purpose of the 'return' keyword in a function?", "options": ["Repeats the function", "Stops the program", "Returns a value to the caller", "Prints text to the console"], "answer": "Returns a value to the caller", "explanation": "'return' sends a value back to whoever called the function."},
        {"q": "What is a 'closure' in Swift?", "options": ["A way to close an app", "A self-contained block of code that can be passed around", "A type of variable", "A way to end a function"], "answer": "A self-contained block of code that can be passed around", "explanation": "Closures are like anonymous functions. They capture and store references to variables."},
        {"q": "What does '$0' mean inside a closure?", "options": ["The first argument of the closure", "The return value", "A syntax error", "The closure itself"], "answer": "The first argument of the closure", "explanation": "$0 is shorthand for the first parameter, $1 for second, etc."},
        {"q": "What is the correct syntax to define a function that takes a String and returns an Int?", "options": ["func convert(s: String) -> Int", "func convert(String s) -> Int", "function convert(s: String): Int", "def convert(s: String) -> Int"], "answer": "func convert(s: String) -> Int", "explanation": "Swift functions use 'func name(param: Type) -> ReturnType' syntax."},
        {"q": "What are 'argument labels' in Swift functions?", "options": ["The names used when calling a function", "The internal variable names", "Comments before functions", "Return type names"], "answer": "The names used when calling a function", "explanation": "Example: func greet(person name: String) — 'person' is the argument label used in calls."},

        # =============================================
        # SWIFT SPECIFIC FEATURES
        # =============================================
        {"q": "What does the 'lazy' keyword do for a variable in Swift?", "options": ["Makes the variable slow to access", "The variable is only computed when first accessed", "Deletes the variable from memory", "Makes the variable a constant"], "answer": "The variable is only computed when first accessed", "explanation": "A lazy property's initial value isn't calculated until it's first used — saves resources."},
        {"q": "What does the 'defer' keyword do?", "options": ["Executes code right before a function exits", "Delays app execution", "Cancels a download", "Creates a new function"], "answer": "Executes code right before a function exits", "explanation": "'defer' schedules a block to run when execution leaves the current scope — great for cleanup."},
        {"q": "What is the correct way to write a single-line comment in Swift?", "options": ["# Comment", "// Comment", "/* Comment", "-- Comment"], "answer": "// Comment", "explanation": "Single-line comments use // and multi-line comments use /* ... */."},
        {"q": "What does 'mutating' mean on a function inside a Struct?", "options": ["The function cannot be called", "The function is allowed to modify properties within the struct", "The function deletes the struct", "The function is for display only"], "answer": "The function is allowed to modify properties within the struct", "explanation": "Since structs are value types, methods need the 'mutating' keyword to modify properties."},
        {"q": "What is an 'enum' in Swift?", "options": ["A type of array", "A group of related values defined as a common type", "A function modifier", "A way to create loops"], "answer": "A group of related values defined as a common type", "explanation": "Enums define a common type for a group of related values, like CompassDirection.north."},
        {"q": "What is a 'computed property' in Swift?", "options": ["A property stored in memory", "A property whose value is calculated each time it is accessed", "A static constant", "A property only for classes"], "answer": "A property whose value is calculated each time it is accessed", "explanation": "Computed properties don't store a value — they provide a getter (and optional setter) to calculate it."},
        {"q": "What does 'typealias' do in Swift?", "options": ["Creates a new data type from scratch", "Gives an existing type a new name/alias", "Converts between types", "Creates a type error"], "answer": "Gives an existing type a new name/alias", "explanation": "Example: typealias AudioSample = UInt16 — creates a readable alias."},
        {"q": "What is the purpose of 'extensions' in Swift?", "options": ["To add new functionality to existing types", "To extend the app runtime", "To increase memory", "To delete old code"], "answer": "To add new functionality to existing types", "explanation": "Extensions let you add methods, computed properties, and more to existing types — even types you don't own."},
    ],

   "Section 3: OOP": [
        {"q": "What is the main difference between Struct and Class in Swift?", "options": ["Struct is reference type, Class is value type", "Struct is value type, Class is reference type", "They are the same", "Struct supports inheritance"], "answer": "Struct is value type, Class is reference type", "explanation": "Structs are copied when passed (value type); classes share a reference (reference type)."},
        {"q": "Which OOP concept hides implementation details?", "options": ["Inheritance", "Polymorphism", "Encapsulation", "Abstraction"], "answer": "Encapsulation", "explanation": "Encapsulation bundles data and methods together and restricts direct access to internals."},
        {"q": "The 'override' keyword is used to...", "options": ["Create a new function", "Replace a function from the parent class", "Delete a function", "Execute a function"], "answer": "Replace a function from the parent class", "explanation": "'override' lets a subclass provide its own implementation of a method inherited from a superclass."},
        {"q": "What is Inheritance?", "options": ["A class's ability to pass its properties to another class", "The ability to hide data", "The process of creating objects", "A way to delete classes"], "answer": "A class's ability to pass its properties to another class", "explanation": "Inheritance allows a subclass to adopt properties, methods, and behavior from a superclass."},
        {"q": "In Swift, a class can inherit from how many superclasses?", "options": ["One", "Two", "Unlimited", "Depends on RAM"], "answer": "One", "explanation": "Swift supports single inheritance — one class can only inherit from one superclass."},
        {"q": "What does 'init' do inside a Swift class?", "options": ["Ends the program", "Deletes data", "Initializes/prepares initial values", "Connects to a database"], "answer": "Initializes/prepares initial values", "explanation": "'init' is a special method that sets up a new instance with initial property values."},
        {"q": "Polymorphism allows us to...", "options": ["Use one interface for different data types", "Make classes very large", "Lock variables so they can't change", "Speed up internet connections"], "answer": "Use one interface for different data types", "explanation": "Polymorphism lets objects of different classes respond to the same method call differently."},
        {"q": "Which keyword prevents a class from being subclassed?", "options": ["static", "final", "private", "locked"], "answer": "final", "explanation": "A 'final' class cannot be inherited from — no subclasses allowed."},
        {"q": "What is the difference between a 'Property' and a 'Method' in an object?", "options": ["Property is a function, Method is data", "Property is data/attribute, Method is behavior/function", "They are the same", "Property is only for classes"], "answer": "Property is data/attribute, Method is behavior/function", "explanation": "Properties store values (data), methods define actions (behavior)."},
        {"q": "What happens in memory when using a 'Reference Type'?", "options": ["Data is copied to a new variable", "Both variables point to the same memory address", "Memory fills up immediately", "Data is automatically deleted"], "answer": "Both variables point to the same memory address", "explanation": "Reference types share the same underlying instance — changing one affects all references."},
        {"q": "What is a 'Deinitializer' (deinit) in Swift?", "options": ["A function to create objects", "A function called just before a class instance is deallocated", "A function to copy data", "A function to update UI"], "answer": "A function called just before a class instance is deallocated", "explanation": "'deinit' is called right before an instance is freed from memory — used for cleanup."},
        {"q": "What is true about a 'Computed Property'?", "options": ["It only stores static values", "Its value is calculated each time the property is accessed", "It's the same as a 'let' constant", "It can only be used inside classes"], "answer": "Its value is calculated each time the property is accessed", "explanation": "Computed properties don't store values — they compute them on the fly."},
        {"q": "The concept of 'Abstraction' aims to...", "options": ["Make code longer", "Show essential functionality and hide complexity", "Connect the app to a server", "Automatically remove bugs"], "answer": "Show essential functionality and hide complexity", "explanation": "Abstraction simplifies complex reality by modeling classes appropriate to the problem."},
        {"q": "In Swift, the keyword 'super' is used to...", "options": ["Make a class 'super'", "Access methods or properties from the parent class", "Speed up app performance", "Exit the application"], "answer": "Access methods or properties from the parent class", "explanation": "'super' lets you call methods, properties, or subscripts from the parent (super) class."},
        {"q": "What is the difference between a 'Static Method' and an 'Instance Method'?", "options": ["Static is called on the class itself, Instance is called on an object", "Instance is faster than Static", "Static is only for numbers", "There is no difference"], "answer": "Static is called on the class itself, Instance is called on an object", "explanation": "Static methods belong to the type. Instance methods belong to a specific instance of that type."},
        {"q": "What is a 'Protocol' in Swift?", "options": ["A blueprint for methods or properties that must be implemented", "A way to manage internet connections", "A way to store user data", "A way to change app themes"], "answer": "A blueprint for methods or properties that must be implemented", "explanation": "A protocol defines a set of requirements that conforming types must implement."},
        {"q": "A class that inherits from another class is called a...", "options": ["Superclass", "Subclass", "Rootclass", "Baseclass"], "answer": "Subclass", "explanation": "The inheriting class is the 'subclass'; the class it inherits from is the 'superclass'."},
        {"q": "What are the four main pillars of OOP?", "options": ["Encapsulation, Inheritance, Polymorphism, Abstraction", "Array, List, Set, Dictionary", "Swift, Objective-C, Java, Python", "Variables, Functions, Loops, Conditions"], "answer": "Encapsulation, Inheritance, Polymorphism, Abstraction", "explanation": "These four pillars are the fundamental concepts of Object-Oriented Programming."},
        {"q": "What does the keyword 'self' refer to?", "options": ["The current instance of the class/struct", "Closes the application", "Creates a copy of the class", "Prints the variable name"], "answer": "The current instance of the class/struct", "explanation": "'self' refers to the specific instance calling the method — like 'this' in other languages."},
        {"q": "What is 'ARC' (Automatic Reference Counting) in Swift?", "options": ["A graphics library", "Swift's memory management system that automatically frees unused class instances", "A type of loop", "An app review process"], "answer": "Swift's memory management system that automatically frees unused class instances", "explanation": "ARC tracks how many references point to an object and frees it when the count reaches zero."},
    ],

    "Section 4: Bonus (Design/UX)": [
        {"q": "Apple's main UI Design principle is HIG. What does it stand for?", "options": ["High Interface Guide", "Human Interface Guidelines", "Helpful Interface Graphics", "Human Integrated Goal"], "answer": "Human Interface Guidelines", "explanation": "HIG = Human Interface Guidelines, Apple's design standards document."},
        {"q": "The most crucial feature for a coworking space booking app is...", "options": ["Price & facility filters", "Colorful backgrounds", "Heavy animations", "Chat bot"], "answer": "Price & facility filters", "explanation": "Users need to filter by price and facilities to find suitable spaces quickly."},
        {"q": "In UI design, what is 'Affordance'?", "options": ["The cost of making a design", "Visual cues that indicate how an object is used", "Image loading speed", "Bright colors"], "answer": "Visual cues that indicate how an object is used", "explanation": "Affordance is a visual hint — like a button looking 'pressable'."},
        {"q": "Which is an example of Apple's 'Consistency' design principle?", "options": ["Using different fonts on every page", "Using the same symbols and styles throughout the app", "Randomly moving the main menu", "Removing navigation buttons"], "answer": "Using the same symbols and styles throughout the app", "explanation": "Consistency means using familiar patterns and icons throughout the entire app."},
        {"q": "What is the main goal of 'User Research' before building an app?", "options": ["Setting the app price", "Understanding user needs, behaviors, and problems", "Finding investors", "Counting lines of code"], "answer": "Understanding user needs, behaviors, and problems", "explanation": "User research ensures the app actually solves real user problems."},
        {"q": "What is 'Dark Mode' in the context of UX?", "options": ["The app only works at night", "A dark color scheme that reduces eye strain", "App mode when offline", "A feature to hide data"], "answer": "A dark color scheme that reduces eye strain", "explanation": "Dark Mode uses darker colors to reduce eye strain, especially in low-light environments."},
        {"q": "The 'Feedback' principle in UI means...", "options": ["Telling the user the result of their action", "Asking for App Store ratings every minute", "Contacting customer service", "Waiting for email replies"], "answer": "Telling the user the result of their action", "explanation": "Good feedback confirms actions — like a button changing color when tapped."},
        {"q": "What does 'Accessibility' mean in app design?", "options": ["Easy download access", "Design usable by everyone, including people with disabilities", "Password security", "Small file size"], "answer": "Design usable by everyone, including people with disabilities", "explanation": "Accessibility ensures all users can use the app, including those with visual, motor, or hearing challenges."},
        {"q": "In Apple's principles, 'Clarity' means...", "options": ["Text should be readable and icons should have clear meaning", "The screen should be very bright", "The app should be transparent", "Using many decorative images"], "answer": "Text should be readable and icons should have clear meaning", "explanation": "Clarity means every element communicates its purpose clearly without confusion."},
        {"q": "Which of the following is an example of 'Bad UX'?", "options": ["Easy-to-find navigation", "Buttons that are too small to tap", "Fast loading times", "Easy-to-understand language"], "answer": "Buttons that are too small to tap", "explanation": "Tiny buttons frustrate users and make interaction difficult — a classic UX problem."},
    ]
    
}